# Values formatted like "_env:ENV_VAR_NAME:default_value" can be overridden by the specified environment variable.
# See https://github.com/yesodweb/yesod/wiki/Configuration#overriding-configuration-values-with-environment-variables

static-dir:     "_env:STATIC_DIR:static"
host:           "_env:HOST:*4" # any IPv4 host
port:           "_env:PORT:80"
approot:        "_env:APPROOT:civ.thinking-machines.net:80"
ip-from-header: "_env:IP_FROM_HEADER:false"

# Optional values with the following production defaults.
# In development, they default to the inverse.
#
# development: false
# detailed-logging: false
# should-log-all: false
# reload-templates: false
# mutable-static: false
# skip-combining: false

database:
  database: "_env:MYSQL_DATABASE:db47735"
  password: "_env:MYSQL_PASSWORD:grisdiC_"
  host:     "_env:MYSQL_HOST:127.0.0.1"
  user:     "_env:MYSQL_USER:db47735"
  port:     "_env:MYSQL_PORT:3306"
  poolsize: "_env:MYSQL_POOLSIZE:10"

copyright: (c) 2015 Reitisoft
#analytics: UA-YOURCODE
