Default: &defaults
  database: Civ.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: Civ_test.sqlite3
  <<: *defaults

Staging:
  database: Civ_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: Civ_production.sqlite3
  poolsize: 100
  <<: *defaults
